void SDL_PrintError (const char * message);
void MySQL_PrintError (const char * message, MYSQL mysql);
void CloseSDLMySQL (SDL_Texture ** texture, SDL_Renderer ** renderer, SDL_Window ** window, MYSQL * mysql);
void version ();
int connectDataBase (MYSQL * mysql);
int initSDL (MYSQL * mysql);
int createWindow (SDL_Texture ** texture, SDL_Renderer ** renderer, SDL_Window ** window, MYSQL * mysql, int x, int y);
int createRenderer (SDL_Texture ** texture, SDL_Renderer ** renderer, SDL_Window ** window, MYSQL * mysql);
int loadBMP (SDL_Texture ** texture, SDL_Renderer ** renderer, SDL_Window ** window, MYSQL * mysql, const char * img, SDL_Surface ** surface);
int createTexture (SDL_Texture ** texture, SDL_Renderer ** renderer, SDL_Window ** window, MYSQL * mysql, SDL_Surface ** surface);
int loadTexture (SDL_Texture ** texture, SDL_Renderer ** renderer, SDL_Window ** window, MYSQL * mysql, int x, int y, SDL_Rect * rectangle);
int updateRenderer (SDL_Texture ** texture, SDL_Renderer ** renderer, SDL_Window ** window, MYSQL * mysql, SDL_Rect * rectangle);
